[global]
# Streamlit Cloud Configuration for Resume Relevance Check System

[server]
headless = true
port = 8501
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"

[browser]
gatherUsageStats = false
